In [1]:
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans

In [10]:
path = "../data/bronze/bus.xlsx"

In [11]:
district = pd.read_excel(path,sheet_name=1)

In [127]:
district= district[district["0a. Has committed ESBs?"]== 'yes']

In [ ]:
df_filtre = district[['3i. Percent of fleet that is electric',
                      '4f. Median household income',
                      '4g. Percent of population below the poverty level'
                      ]]

In [13]:
df_filtre.isna().mean() * 100

3i. Percent of fleet that is electric                 1.562740
4f. Median household income                          33.319670
4g. Percent of population below the poverty level    33.017369
dtype: float64

In [14]:
df_propre = df_filtre.dropna()

In [15]:
df_propre.head(5)

,3i. Percent of fleet that is electric,4f. Median household income,4g. Percent of population below the poverty level
0,0.242424,45699.0,0.171
3,0.166667,62722.0,0.077
4,0.000000,56121.0,0.161
5,0.000000,95406.0,0.070
6,0.000000,105335.0,0.050

In [16]:
df_propre.corr()

,3i. Percent of fleet that is electric,4f. Median household income,4g. Percent of population below the poverty level
3i. Percent of fleet that is electric,1.000000,0.000574,0.027188
4f. Median household income,0.000574,1.000000,-0.634179
4g. Percent of population below the poverty level,0.027188,-0.634179,1.000000

In [ ]:
cols = [
            '3i. Percent of fleet that is electric',
            '4f. Median household income',
            '4g. Percent of population below the poverty level'
]

for col in cols:
    df_filtre[col] = df_filtre[col].fillna(df_filtre[col].median())

/var/folders/gf/s4y8jpss6175xrsb0x_hpsmw0000gn/T/ipykernel_23269/3067223022.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_filtre[col] = df_filtre[col].fillna(df_filtre[col].median())

In [18]:
df_propre.isna().mean() * 100

3i. Percent of fleet that is electric                0.0
4f. Median household income                          0.0
4g. Percent of population below the poverty level    0.0
dtype: float64

In [19]:
df_propre.head(10)

,3i. Percent of fleet that is electric,4f. Median household income,4g. Percent of population below the poverty level
0,0.242424,45699.0,0.171
3,0.166667,62722.0,0.077
4,0.000000,56121.0,0.161
5,0.000000,95406.0,0.070
6,0.000000,105335.0,0.050
9,0.000000,62432.0,0.085
10,0.000000,40732.0,0.216
11,0.000000,108313.0,0.037
13,0.000000,46750.0,0.162
14,0.000000,40516.0,0.229

In [20]:
features_stdr = [
            '3i. Percent of fleet that is electric',
            '4f. Median household income',
            '4g. Percent of population below the poverty level'
]

In [21]:
scaler = StandardScaler()

df_propre[features_stdr] = scaler.fit_transform(df_propre[features_stdr])

/var/folders/gf/s4y8jpss6175xrsb0x_hpsmw0000gn/T/ipykernel_71493/3405699004.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_propre[features_stdr] = scaler.fit_transform(df_propre[features_stdr])

In [22]:
df_propre.head(5)

,3i. Percent of fleet that is electric,4f. Median household income,4g. Percent of population below the poverty level
0,0.852411,-0.840763,0.685981
3,0.557460,-0.227916,-0.609955
4,-0.091433,-0.465559,0.548116
5,-0.091433,0.948746,-0.706461
6,-0.091433,1.306202,-0.982192

In [ ]:
df_propre.to_csv('../TP5/anomalies.csv',index=False)